### ISSUE TITLE
Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.

### ISSUE THREAD

**Issue by namntx** [shadcn/taxonomy#100]
I have error when run `pnpm dev`

> <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'markdown-wasm/dist/markdown.node.js' in '/Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/markdown'
> <w> while resolving 'markdown-wasm/dist/markdown.node.js' in /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/markdown as file
> <w>  at resolve esm file markdown-wasm/dist/markdown.node.js
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/markdown/markdown.js
> <w>  at file /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/markdown/markdown.js
> <w>  at resolve esm file ./markdown/markdown.js
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/index.js
> <w>  at file /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/index.js
> <w>  at resolve esm file @contentlayer/core
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/node_modules/.pnpm/next-contentlayer@0.2.9_esbuild@0.14.54_next@13.2.3_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
> <w>  at file /Users/namntx/Desktop/benvev2/node_modules/.pnpm/next-contentlayer@0.2.9_esbuild@0.14.54_next@13.2.3_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
> <w>  at resolve esm file ./plugin.js
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/node_modules/.pnpm/next-contentlayer@0.2.9_esbuild@0.14.54_next@13.2.3_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
> <w>  at file /Users/namntx/Desktop/benvev2/node_modules/.pnpm/next-contentlayer@0.2.9_esbuild@0.14.54_next@13.2.3_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
> <w>  at resolve esm file next-contentlayer
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/next.config.mjs
> <w>  at file /Users/namntx/Desktop/benvev2/next.config.mjs
> <w>  at resolve commonjs /Users/namntx/Desktop/benvev2/next.config.mjs
> <w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/getConfig/index.js for build dependencies failed at 'import(`file://${modulePath}?x=${new Date()}`)'.
> <w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
> <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'markdown-wasm/dist/markdown.node.js' in '/Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/markdown'
> <w> while resolving 'markdown-wasm/dist/markdown.node.js' in /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/markdown as file
> <w>  at resolve esm file markdown-wasm/dist/markdown.node.js
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/markdown/markdown.js
> <w>  at file /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/markdown/markdown.js
> <w>  at resolve esm file ./markdown/markdown.js
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/index.js
> <w>  at file /Users/namntx/Desktop/benvev2/node_modules/.pnpm/@contentlayer+core@0.2.9_esbuild@0.14.54/node_modules/@contentlayer/core/dist/index.js
> <w>  at resolve esm file @contentlayer/core
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/node_modules/.pnpm/next-contentlayer@0.2.9_esbuild@0.14.54_next@13.2.3_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
> <w>  at file /Users/namntx/Desktop/benvev2/node_modules/.pnpm/next-contentlayer@0.2.9_esbuild@0.14.54_next@13.2.3_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
> <w>  at resolve esm file ./plugin.js
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/node_modules/.pnpm/next-contentlayer@0.2.9_esbuild@0.14.54_next@13.2.3_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
> <w>  at file /Users/namntx/Desktop/benvev2/node_modules/.pnpm/next-contentlayer@0.2.9_esbuild@0.14.54_next@13.2.3_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
> <w>  at resolve esm file next-contentlayer
> <w>  at file dependencies /Users/namntx/Desktop/benvev2/next.config.mjs
> <w>  at file /Users/namntx/Desktop/benvev2/next.config.mjs
> <w>  at resolve commonjs /Users/namntx/Desktop/benvev2/next.config.mjs
>

**Comment by keegn** [comment]
Same here. Was causing my builds to fail on Vercel. I ended up removing Contentlayer but would like to find a fix

**Comment by leonardodincalci** [comment]
how do you solved it?

**Comment by samuelrondot** [comment]
Having the same problem.

**Comment by Rostyk27** [comment]
this answer helped me
https://github.com/contentlayerdev/contentlayer/issues/129#issuecomment-1116879647

**Comment by my3t** [comment]
1. Rename to next.config.js
2. Change your config to this.

```
// import { createContentlayerPlugin } from "next-contentlayer"
const { createContentlayerPlugin } = require("next-contentlayer");

// import "./env.mjs"
import("./env.mjs");

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  images: {
    domains: ["avatars.githubusercontent.com", "images.unsplash.com"],
  },
  experimental: {
    // appDir: true,
    serverComponentsExternalPackages: ["@prisma/client"],
  },
}

const withContentlayer = createContentlayerPlugin({
  // Additional Contentlayer config options
});

// export default withContentlayer(nextConfig)
module.exports = withContentlayer(nextConfig);
```

content-layer 0.3.3
