### ISSUE TITLE
When logged in, users can still access the login page

### ISSUE THREAD

**Issue by sharikhahmed** [shadcn/taxonomy#14]
to recreate the above issue, login and go to the `/dashboard` endpoint, go back to home page you still see a login button which should not be there and also when you click on it you can access login page even though the users is authenticated, i can't find a usecase where this is a feature instead of bug, lmk if i am msising anything

**Comment by shadcn** [comment]
@sharikhahmed this is a bug. I have a fix for this on the way. See also #11

**Comment by sharikhahmed** [comment]
@shadcn , this repo has been a great help while learning next 13 first of all thanks for contributing us to learn!  ill create a new branch and try to solve this bug, I have already cloned this project, and I have read the repo code a little bit, but I don't have the full context, as you have written the whole code I wanted to know from you on  how to go about tackling this issue, my guess is that its a problem with middleware code, not sure have to properly read the code

**Comment by Geczy** [comment]
https://gist.github.com/MarcDiethelm/7303312

https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by shadcn** [comment]
@sharikhahmed I've updated next-auth and fixed this.
