### ISSUE TITLE
Moving globals.css into new project results in syntax error

### ISSUE THREAD

**Issue by 1OGAG** [shadcn/taxonomy#175]
This is a great project that I've been using to try to learn tailwind and nextjs. If I try to use the same global.css stylesheet (no edits) in a different project, I get an error.  Is there some post-processing dependency or something that is required to make this work in other projects? I also copied postcss.config.js,&  tailwind.config.js.  Any ideas are greatly appreciated!

`- error ./styles/globals.css
Syntax error: /Users/a/Desktop/test/site_13/styles/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive. (1:1)

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;
-- inner error --
Syntax error: /Users/a/Desktop/test/site_13/styles/globals.css The `border-border` class does not exist. If `border-border` is a custom class, make sure it is defined within a `@layer` directive. (1:1)

Generated code for /Users/a/Desktop/test/site_13/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[2]!/Users/a/Desktop/test/site_13/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[12].use[3]!/Users/a/Desktop/test/site_13/styles/globals.css
`

**Comment by Ayothegod** [comment]
did you install all the dependency?

**Comment by 1OGAG** [comment]
This is a head-up for anyone trying to use this .css in an external project. I installed all tailwind dependencies with the latest nextjs and got an error. After using the exact version numbers from shadcn's package.json everything worked. So if you encounter an issue like this check your version numbers...
