### ISSUE TITLE
Add auto-login detect on home page 

### ISSUE THREAD

**Issue by pawitpr** [shadcn/taxonomy#176]
To 
![Screenshot Capture - 2023-07-03 - 22-24-10](https://github.com/shadcn/taxonomy/assets/123424956/13328ec7-a9df-485c-b6d0-f2d1aafacb77)
This ![Screenshot Capture - 2023-07-03 - 22-29-26](https://github.com/shadcn/taxonomy/assets/123424956/0f83a550-10fb-41a2-b350-3998587d42d5)

A small feature needed

**Comment by Ayothegod** [comment]
Hi, can I be assigned this issue?

**Comment by sanchitttt** [comment]
I want to contribute in resolving this issue, I'm new to open source, how can I do this?

**Comment by pawitpr** [comment]
Where is main page file?

can't found on /app and /page directory

**Comment by Prashraj78** [comment]
what i need to do

**Comment by pawitpr** [comment]
> what i need to do

this feature can't be added, because the main page is hidden only owner can change this
