### ISSUE TITLE
Header overlapping modal overlay

### ISSUE THREAD

**Issue by Fecony** [shadcn/taxonomy#28]
When removing post heading is still visible.

Looks like Heading and modal have `z-index: 40`

<img width="1511" alt="Screenshot 2022-11-23 at 17 29 39" src="https://user-images.githubusercontent.com/36774784/203585392-61908d3f-ac71-4f2e-9a60-40ab5d39862f.png">

**Comment by shadcn** [comment]
Fixed. Thank you.
