### ISSUE TITLE
Why opening new route take time?

### ISSUE THREAD

**Issue by nityam01** [shadcn/taxonomy#31]
When clicking on Get Started or any link for the first time, it takes a couple of ms to open. Wasn't that a bad experience? Was it happening because of SSR?
Video link:-
[Video 1](https://www.dropbox.com/s/7vmrdyu1j1wst8t/Screencast%20from%2011-25-2022%2012%3A11%3A27%20AM.webm?dl=0)
[Video 2](https://www.dropbox.com/s/szwkeofxxkb3a77/Screencast%20from%2011-25-2022%2012%3A36%3A48%20AM.webm?dl=0)

**Comment by shadcn** [comment]
Oh yeah there's an issue when using dynamic headers in the layout. It seems like we're seeing a cache miss for all route navigation. A bit hard to debug since I can't reproduce this on local.

I pushed a temp fix for it. Should be faster now. Let me know.
