### ISSUE TITLE
https://tx.shadcn.com/docs/documentation/contentlayer -> not found

### ISSUE THREAD

**Issue by sharikhahmed** [shadcn/taxonomy#38]
when I click on contentLayer in documentation it go to a 404 page, 
<img width="902" alt="Screenshot 2022-11-27 at 10 21 37 AM" src="https://user-images.githubusercontent.com/97469930/204119791-fb3d90bc-05e9-4583-9c07-a8289d326e8a.png">

**Comment by shadcn** [comment]
This is still in the works.
