### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by edgarasben** [shadcn/taxonomy#47]
Getting an error when trying to log in with email:

1. Enter email
2. Receive email link
3. Click link from email and receive error:

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/725324/204680949-a146ddbe-55ef-4619-b5b9-ff68e86d1821.png">

**Comment by ericshively** [comment]
+1. Error is on the /dashboard page (presumably where the email confirmation redirect is to)

**Comment by edgarasben** [comment]
Neither works for me actually.

**Comment by shadcn** [comment]
Looking into it.

**Comment by shadcn** [comment]
Fixed.
