### ISSUE TITLE
Deos Your post was not saved. Please try again. error message makes sense for login failure

### ISSUE THREAD

**Issue by sharikhahmed** [shadcn/taxonomy#50]
this is a small issue, but the login fail error toast message should be chaged
<img width="499" alt="Screenshot 2022-12-01 at 9 33 17 PM" src="https://user-images.githubusercontent.com/97469930/205101092-755660cf-bb43-4088-a36f-1de4b5a53821.png">

**Comment by shadcn** [comment]
This was fixed here #39
