### ISSUE TITLE
Fallback avatar visible with avatar

### ISSUE THREAD

**Issue by Fecony** [shadcn/taxonomy#59]
Radix fallback component is visible with avatar image

Most likely because you are [using](https://github.com/shadcn/taxonomy/blob/main/ui/avatar.tsx#L33) `next/image` component and not Radix `<Avatar.Image />`. So fallback is triggered?

<img width="394" alt="Screenshot 2022-12-23 at 16 10 21" src="https://user-images.githubusercontent.com/36774784/209349390-ffbff252-af6c-415f-a84e-14ff8a710e8a.png">

**Comment by shadcn** [comment]
I pushed a fix for this. Thanks for the heads up.

**Comment by lmachens** [comment]
> I pushed a fix for this. Thanks for the heads up. 

In your commit, you render the user image only if it is set and the fallback of its not set.
But what happens, if the image is set, but couldn't be loaded? The fallback can not be triggered, because it's not rendered.
