### ISSUE TITLE
Question: purpose of project?

### ISSUE THREAD

**Issue by sethsnel** [shadcn/taxonomy#6]
Question: is this project meant to:
- showcase all capabilities of the latest nextjs release;
- a project starter/template;
- a ready to use CMS;
- all of the above?

**Comment by patrickedqvist** [comment]
I starred this project to see examples of the new capabilities together with some of the more popular next-js frameworks, for instance, next-auth. Thank you for open-sourcing this as well.

**Comment by shadcn** [comment]
@sethsnel Right now, I'm using this project as an experiment to see how a modern app (with features like authentication, subscription, API routes, static pages for docs ...etc) would work in Next.js 13 and server components.

I'll be posting updates and issues here.

A few people have asked me to turn this into a starter. We could do that once the new features are out of beta.

**Comment by sethsnel** [comment]
Thanks for the explanation!
Perhaps mention this briefly in the README, I could create a PR for that.
