### ISSUE TITLE
Question : User Authentication

### ISSUE THREAD

**Issue by bfourgeaud** [shadcn/taxonomy#7]
Hello,

I am very interested in your project as I wanted to start migrating some projet to Next13 and the app directory.
I was wondering how you handle the authentication as I am stuggling with that subject. I saw you removed the authentication in a previous commit. Why ? Have you got some ideas how to make it work ?
I am very interested to see how you will manage that, I'll folllow closely your work ;)

Thanks,

**Comment by agustif** [comment]
Hey @bfourgeaud this issue n NextAuth can help

https://github.com/nextauthjs/next-auth/issues/5647

**Comment by shadcn** [comment]
@bfourgeaud I disabled authentication temporarily because of a bug with Prisma and the site was getting a lot of traffic. :)

I added authentication back now but we're still figuring out the issue with Prisma and Next.js.

You can check out how the authentication works. We're using NextAuth.js.

**Comment by bfourgeaud** [comment]
I'll have a look on NextAuth issue and how you handle that with the new server/client-components.
Thank you for your work, I'll close the "issue" as it isn't one ;)

**Comment by Geczy** [comment]
what's the bug? @shadcn

**Comment by shadcn** [comment]
@Geczy https://github.com/prisma/prisma/issues/16117

**Comment by jameswong3388** [comment]
@shadcn, sry for bothering but I am having the same issue with authentication using NextAuth.Js (Github Provider). Everything works perfectly locally, but when I deployed to production, I received the following 

![image](https://user-images.githubusercontent.com/87692325/205522760-a98a9f99-fa33-4d21-9288-29418f0dad69.png)

I had the same configuration as yours, not sure if you had the same problem before. 
Any help would be much appreciated! THX
