### ISSUE TITLE
PFA: Getting this error when clicked on login button.

### ISSUE THREAD

**Issue by theDheerajjha** [shadcn/taxonomy#78]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/52864945/230794924-fc69e731-9beb-4113-b4b8-4acfd42f21f0.png">

**Comment by pospile** [comment]
`npx prisma generate` with properly set .env file should do the trick

**Comment by theDheerajjha** [comment]
Getting this error now @pospile 
<img width="912" alt="image" src="https://user-images.githubusercontent.com/52864945/230987886-918555f2-28e4-43d6-b691-f0811df5bb6b.png">

**Comment by pospile** [comment]
Error is pretty self explanatory. Missing env variable with postmark api key. Sign up and obtain a key.

**Comment by keegn** [comment]
I'm getting a callback error when trying to authenticate using github on localhost. My github oauth app callback url is currently set to `http://localhost:3000/api/auth/callback/github`. Wondering if anyone has experienced this?

**Comment by krishnu9** [comment]
@theDheerajjha were you able to solve this? Did you create a Postmark API key ?
