### ISSUE TITLE
Saving a post does not show the saved post automatically

### ISSUE THREAD

**Issue by Fredkiss3** [shadcn/taxonomy#8]
When we go to the editor page for one post, when we click on "save",  go back to the dashboard, and return to the editor page it shows the old post.

Since next 13 does a soft navigation on route push or back, you could call `router.refresh()` on save to force it to refetch the data.

I've attached a screenshot :
https://user-images.githubusercontent.com/38298743/200118896-baa87a7d-eabf-4a02-8490-867fdc8d3649.mov

PS :
And one simple way to have loading state without creation one yourself is to use `React.useTransition` it provides you with a pending state :

```tsx
const [isSaving, startTransition] = React.useTransition();

async function onSubmit(data: FormData) {
	startTransition(() => {
		// you do your fetch call here...

		router.refresh();
	});
}

// ... rest of your code
```

**Comment by shadcn** [comment]
@Fredkiss3 I just learnt about using `useTransition` from timneutkens yesterday. I'll add this fix. Merci 👍

**Comment by shadcn** [comment]
@Fredkiss3 I pushed a fixed for this.
