### ISSUE TITLE
Call redirect function on dashboard layout if user not found 

### ISSUE THREAD

**Issue by Fredkiss3** [shadcn/taxonomy#9]
This is not really an issue but a suggestion : 
You probably should call redirect to login for users on the dashboard if the user is not in the session :

```tsx
import { redirect } from 'next/navigation';

// ... rest of the code

export default async function DashboardLayout({
  children,
}: DashboardLayoutProps) {
  const user = await getUser()

  if (!user) {
	// here
    redirect('/login');
  }

  return ( ... );
}
```
The docs on redirect are here : https://beta.nextjs.org/docs/api-reference/redirect

**Comment by shadcn** [comment]
I've updated next-auth and fixed this using middleware. Thanks @Fredkiss3 :)
