### ISSUE TITLE
[FEAT REQUEST] Dark Mode functionality

### ISSUE THREAD

**Issue by abhinav2712** [shadcn/taxonomy#90]
I feel like this website needs dark mode functionality, Assign me this issue so that I can give it a try!

**Comment by suryanshsoni120** [comment]
If this issue is still open, can I work on it?

**Comment by abhinav2712** [comment]
@suryanshsoni120 Bro I was here first, but none of the maintainers are responding

**Comment by shadcn** [comment]
Please note that I'm working on updating the site to the latest ui.shadcn.com components. 

This will bring in automatic dark mode support with no additional work. 

Thank you both for your help.

**Comment by abhinav2712** [comment]
@shadcn Okay, if there's any else help, let me know, I find this project really interesting

**Comment by ksgokul2501** [comment]
This issue should be closed.
